version: "3.4"
services:
  frontend_static:
    container_name: mug_frontend_static
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - mug_frontend_static:/frontend/dist
  backend:
    container_name: mug_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/mug/.env
    expose:
      - 8080
    command: gunicorn mug.wsgi:application --bind 0.0.0.0:8080 --log-level debug
    volumes:
      - mug_static:/app/static
      - mug_media:/app/media
    depends_on:
      - postgres
    networks:
      - internal
  postgres:
    image: postgres:alpine
    container_name: mug_postgres
    volumes:
      - mug_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/mug/db.env
    environment:
      POSTGRES_DB: Mug
      POSTGRES_USER: postgres
    networks:
      - internal
  nginx:
    image: nginx:alpine
    container_name: mug_nginx
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - mug_frontend_static:/frontend/dist
      - mug_static:/static
      - mug_media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mug.rule=Host(`mug.micheleawada.com`)"
      - "traefik.http.routers.mug.entrypoints=websecure"
      - "traefik.http.routers.mug.tls=true"
      - "traefik.http.routers.mug.tls.certresolver=letsencrypt"
    networks:
      - internal
      - traefikproxy

volumes:
  mug_postgres_data:
  mug_media:
  mug_static:
  mug_frontend_static:

networks:
  internal:
  traefikproxy:
    name: traefikproxy
    external: true
